- README.md
> Update README.md to fix typo in word accessibility

- README.md
Added a list of links showcasing assistive technology in action.
> Assistive technology in action

- CODE_OF_CONDUCT.md
Hey @lulen11 and @sarahesbie 
This CODE_OF_CONDUCT is used the latest version from [Contributor Covenant](https://www.contributor-covenant.org/) website.
I used email to contact is CLG's email: [hello@codelikeagirl.com](mailto:hello@codelikeagirl.com), hopefully it's correct :)
Please help me review this repo and merge it if its possible 😍
> Created CODE_OF_CONDUCT.md for CLG Hacktoberfest 2023

- index.html
- styles.css
Hey @sarahesbie, what do you think? Next step could be bringing in the readme content for all to read on the frontend and mapping out a bit of a web project checklist for accessibility ?
Question: should we use Sass in this repo so we can organise colours etc by variables or keep it as basic CSS for more contributors to play around as they please? 😃
> Setting up home layout and styles

- styles.css
Hey Sarah and Lara
I've added some CSS custom properties for the colour palette...I thought I'd start with something small and fingers crossed I've done it right! Let me know if you need any changes 😄
> Add colour palette as CSS custom properties

- styles.css
please merge this pull request under hactoberfest.
> did some changes in the color scheme of the project to make it visually more appealing to the users.

- README.md
Added 'Assistive Technology' section to README to include resources for screen readers, voice controllers and screen magnifiers and links to templates to use as a guide when testing. 
Moved 'Assistive Technology' in action section into it as a sub-section.
Also added a couple more resources in the Tools and Resources section.
Would you mind adding the Hacktoberfest tag to this PR (and maybe my previous one if it's still possible to edit it now?)
Thanks! ✨
> Lauren issue 21

- styles.css
Since the site is about accessibility, I thought it would be good to make sure it was very accessible. Adjusted link styling for improved contrast and also simplified to the most recognised blue and underline. 
I also adjusted other colours a bit so I could run them through a contrast checker and make sure they hit WCAG standards.
Reduced line length for readability.
> Style links

- README.md
- styles.css
This PR is associated with this issue: https://github.com/codelikeagirlau/accessibility-resources/issues/24
Out put will be like this:
> README Enhancement - Added Table of Contents and back to top button

- README.md
This PR is relating to this issue: https://github.com/codelikeagirlau/accessibility-resources/issues/26
> README Updating Content - Added People to Follow in Web Accessibility

- README.md
- manifesto.html
- web-developer-pledge.html
Heya @lulen11 - I've added some page stubs and started dropping content into an accessibility manifesto and web developers pledge.
I know in our catchup we suggested these two could be on the same page. It was really helpful to me to keep them seperate for now, but I'm keen to see how they might evolve. 
This is a start for both of these - I'm keen to get some discussions going about how we can develop the content of both of these.
> Feature branch 20 - manifesto & pledge

- about.html
- styles.css
Hey @sarahesbie and team, what do you think? This one [creates a new about page](https://github.com/codelikeagirlau/accessibility-resources/issues/32) explaining what this is all about and includes links for onlookers to contribute too
> New about page and content!

- README.md
- index.html
- web-developer-pledge.html
This PR is used to gradually shift content from README to index.html. 
Below are list of change:
Screenshot for review:
> Move Table of Content to index.html to adding new content page

- README.md
- index.html
- sub-page/accessibility-course.html
- sub-page/web-developer-pledge.html
- web-developer-pledge.html
This PR has:
Screenshot for review:
> Adding accessibility courses page

- index.html
- manifesto.html
- styles.css
- web-developer-pledge.html
This nav is WIP and can be styled & positioned once we put together a page template (@laurenchamps is on it ;) ) but thought it might be useful to have it in there for when we're working through the pages anyway
> Navigation

- about.html
- index.html
- manifesto.html
- styles.css
- template.html
Replacing previous pull request #38. Add page layout template and apply to existing pages.
This should now resolve the merge conflicts and I've also synced with the more recently accepted PRs and applied the template layout across new pages.
> Issue 31 layout

- about.html
- index.html
- manifesto.html
- styles.css
- sub-page/web-developer-pledge.html
- template.html
* Links nav btn to pledge page
* Updates hover styles on nav links and nav btn - because they're both `.sidebar-nav a` we had some mixup styles being applied between the btn and the default links. 
* Removes accidental repeated styles - we had some repeated style rules that I've since cleared :)
> Updating nav styles

- about.html
- index.html
- manifesto.html
- template.html
Heya Lara - these links were working on the local but were broken on the production site - this fix should make them work on both local and prod fingers crossed!
> fixing broken links in navigation

- sub-page/accessibility-course.html
Ok - I think I have the additions correct this time: 
Parts of the HTML template added to accessibility_course.html: 
TOP OF PAGE
- body
- header
- nav
END OF PAGE
- main 
- footer
All elements within 'section' have been left as they are this is only a formatting exercise so that accessibility-course.html complies with the basic template.html for this project.
> Add HTML template to accessibility-course.html

- about.html
- index.html
- manifesto.html
- sub-page/accessibility-course.html
- sub-page/web-developer-pledge.html
- template.html
- tools-and-resources.html
Create Tools & Resources page and add content from README.
Add link in navigation on all other existing pages plus template.html.
> Issue 42 tools resources

- ACCESSIBILITY_AUDITS.md
- accessibility-audits/01_2023-10-31_audit_sarahesbie.md
- accessibility-audits/AUDIT_TEMPLATE.md
heya @lulen11 
I've added the audit log, a folder for collecting audits and a template people can use.
LMK if you have any questions :)
> 50 accessibility audit log

- about.html
- sub-page/accessibility-course.html
Added my bage and name to the about.html page as per this morning's meeting. 
Seem to have a bunch of other commits here - not entirely sure what I've done but hopefully it's still a functional PR? 
Thanks Shann
> Added badge and name of Shann Roberts to about.html

- sub-page/web-developer-pledge.html
Addressing Issue: "Apply template to Pledge page #57" delegated to Shann in this morning's meeting. 
Pledge page now has correct formating in line with template.html
> Added template.html format to web-developer-pledge.html

- about.html
- index.html
- manifesto.html
- sub-page/accessibility-course.html
- sub-page/web-developer-pledge.html
- template.html
- tools-and-resources.html
Hi! 
I've fixed all the links accross all html pages. 
Also updated each html page to  have correct class ="active" on it's own link.
Also have noticed that we don't appear to have a link from the main sidebar nav to sub-page/accessibility-course.html. Is there a link in another location so the user can access it?
> Fix broken links
